from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('login/', views.user_login, name='login'),
    path("dashboard/", views.dashboard, name="dashboard"),
    path('calendar-events/', views.calendar_events, name='calendar_events'),
    path('project/', views.project, name='project'),
    path('project/tambah/', views.tambah_project, name='tambah_project'),
    path('project/edit/', views.edit_project, name='edit_project'),
    path('project/hapus/<int:id>/', views.hapus_project, name='hapus_project'),
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('kegiatan/calendar-events/', views.calendar_events_kegiatan, name='calendar_events_kegiatan'),
    path('kegiatan/tambah/', views.tambah_kegiatan, name='tambah_kegiatan'),
    path('kegiatan/edit/', views.edit_kegiatan, name='edit_kegiatan'),
    path('kegiatan/hapus/<int:id>/', views.hapus_kegiatan, name='hapus_kegiatan'),
    path('kegiatan/detail/<int:id>/', views.get_kegiatan_detail, name='get_kegiatan_detail'),
    path('subproject/', views.subproject, name='subproject'),
    path('subproject/tambah/', views.tambah_subproject, name='tambah_subproject'),
    path('subproject/edit/', views.edit_subproject, name='edit_subproject'),
    path('subproject/hapus/<int:id>/', views.hapus_subproject, name='hapus_subproject'),
    path("tugas/", views.tugas, name="tugas"),
    path("tugas/upload/", views.upload_tugas, name="upload_tugas"),
    path("tugas/hapus/<int:id>/", views.hapus_tugas, name="hapus_tugas"),
    path('review/', views.review_list, name='review'),
    path('review/tambah/', views.tambah_review, name='tambah_review'),
    path('review/edit/', views.edit_review, name='edit_review'),
    path('review/hapus/<int:id>/', views.hapus_review, name='hapus_review'),
    path('kpi/', views.kpi, name='kpi'),
    path('kpi/<int:pegawai_id>/', views.get_kpi, name='get_kpi'),
    path('kpi/pdf/<int:pegawai_id>/', views.cetak_kpi_pdf, name='cetak_kpi_pdf'),
    path('kpi/cetak/<int:pegawai_id>/', views.cetak_kpi_pdf, name='cetak_kpi_pdf'),
    path('kpi/grafik/<int:pegawai_id>/', views.grafik_pegawai, name='grafik_pegawai'),
    path('pegawai/', views.pegawai, name='pegawai'),
    path('pegawai/tambah/', views.tambah_pegawai, name='tambah_pegawai'),
    path('pegawai/edit/', views.edit_pegawai, name='edit_pegawai'),
    path('pegawai/hapus/<int:id>/', views.hapus_pegawai, name='hapus_pegawai'),
    path('profile/', views.profile_view, name='profile_view'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('logout/', views.logout_view, name='logout'),
]