# Generated by Django 4.0 on 2026-03-27 03:55

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateField()),
                ('akhir', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('selesai', 'Selesai')], default='ongoing', max_length=20)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.pegawai')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.perusahaan')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('mulai', models.DateTimeField()),
                ('akhir', models.DateTimeField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.pegawai')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.project')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('tgl_upload', models.DateTimeField()),
                ('terlambat', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=10)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.subproject')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_revisi', models.DateTimeField()),
                ('catatan', models.TextField()),
                ('status', models.CharField(choices=[('revisi', 'Revisi'), ('selesai', 'Selesai')], max_length=20)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.pegawai')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.tugas')),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.jabatan'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='perusahaan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.perusahaan'),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
