# Generated by Django 4.0 on 2026-04-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='batas_waktu_review',
            field=models.IntegerField(default=3, help_text='Batas waktu review dalam jam'),
        ),
    ]
