# Generated by Django 4.0 on 2026-04-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_perusahaan_batas_waktu_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='status_akun',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('tidak_aktif', 'Tidak Aktif')], default='aktif', max_length=15),
        ),
        migrations.AddField(
            model_name='pegawai',
            name='status_pegawai',
            field=models.CharField(choices=[('magang', 'Magang'), ('tetap', 'Tetap'), ('kontrak', 'Kontrak')], default='tetap', max_length=10),
        ),
    ]
