# Generated by Django 4.0 on 2026-04-16 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_pegawai_status_akun_pegawai_status_pegawai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('mulai', models.DateTimeField()),
                ('akhir', models.DateTimeField()),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kegiatan_dibuat', to='kpi.pegawai')),
                ('pegawai', models.ManyToManyField(related_name='kegiatan', to=settings.AUTH_USER_MODEL)),
                ('perusahaan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.perusahaan')),
            ],
        ),
    ]
