# Generated by Django 4.0 on 2026-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daerah',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='instansi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='kode_pekerjaan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='status_kontrak',
            field=models.CharField(choices=[('kontrak', 'Kontrak'), ('belum_kontrak', 'Belum Kontrak')], default='belum_kontrak', max_length=20),
        ),
    ]
