# Generated by Django 4.0 on 2026-04-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_project_daerah_project_instansi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='perusahaan_administrasi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
