# Generated by Django 4.0 on 2026-04-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_project_perusahaan_administrasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='sharepoint_path',
            field=models.CharField(blank=True, help_text='Path penyimpanan di SharePoint. Kosongkan untuk menggunakan path default.', max_length=500, null=True),
        ),
    ]
