# Generated by Django 4.0 on 2026-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_subproject_sharepoint_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='sharepoint_drive_id',
            field=models.CharField(blank=True, help_text='Drive ID SharePoint perusahaan ini', max_length=255, null=True),
        ),
    ]
