# Generated by Django 4.0 on 2026-05-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0008_perusahaan_sharepoint_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.pegawai'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.pegawai'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='pegawai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.pegawai'),
        ),
    ]
