# Generated by Django 4.0 on 2026-05-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_alter_project_dibuat_oleh_alter_review_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugas',
            name='file_url',
        ),
    ]
